### ISSUE TITLE
User exception is handled as internal error

### ISSUE THREAD

**Issue by Halama** [keboola/processor-create-manifest#24]
Invalid config with `columns` set to string instead of array:
```
{
      "definition": {
        "component": "keboola.processor-create-manifest"
      },
      "parameters": {
        "delimiter": "\t",
        "enclosure": "",
        "incremental": false,
        "columns": "auto"
      }
    }
```

` "errorOutput": "[2018-07-31 10:49:17] CRITICAL: Keboola\\Component\\UserException:Invalid type for path \"root.parameters.columns\". Expected array, but got string`

Error https://connection.keboola.com/admin/utils/logs?file=2018/07/31/12/2018-07-31-12-51-37-5b603f393d468-exception

**Comment by odinuv** [comment]
nj, tady neni catch na userexception https://github.com/keboola/processor-create-manifest/blob/master/src/run.php#L21

**Comment by Halama** [comment]
#22 should fix this too
