### ISSUE TITLE
add destination parameter

### ISSUE THREAD

**Issue by pocin** [keboola/processor-create-manifest#25]
Hi guys, what is the rationale behind not being able to specifiy the "destination" parameter using this processor?

This would be great to have because we could choose other than the default bucket in an aws s3 extractor, for example.

**Comment by odinuv** [comment]
The rationale is to keep things as simple as possible - That's what default bucket is for - define a destination. Yes, we can add another way of defining destination, or we can add two more ways of defining destination....

If you need to put tables in specific "locations", use aliases.
