### ISSUE TITLE
ProcessFailedException cannot stat file

### ISSUE THREAD

**Issue by pivnicek** [keboola/processor-create-manifest#28]
Not sure, but maybe should be a User Exception?
```
No such file or directory  {\"errFile\":\"\/code\/vendor\/symfony\/process\/Process.php\",\"errLine\":223,\"
```

**Comment by ondrejhlavacek** [comment]
How did this happen?

**Comment by pivnicek** [comment]
ah, sorry

https://keboola.slack.com/archives/C09U3R1J4/p1543589168001700

**Comment by ondrejhlavacek** [comment]
properly escape here

https://github.com/keboola/processor-create-manifest/blob/1feeb28f306f4b65b053f1c6eb8bc6f0bf6c5799/src/Component.php#L120
