### ISSUE TITLE
Malformed UTF-8 characters

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/processor-create-manifest#5]
```
Fatal error: 
Uncaught Symfony\Component\Serializer\Exception\UnexpectedValueException: 
Malformed UTF-8 characters, possibly incorrectly encoded 
in /code/vendor/symfony/serializer/Encoder/JsonEncode.php:43
Stack trace:
#0 /code/main.php(98): Symfony\Component\Serializer\Encoder\JsonEncode->encode(Array, 'json')
#1 {main}
thrown in /code/vendor/symfony/serializer/Encoder/JsonEncode.php on line 43
```

no sakra ale nevím, jak se to tam dostalo. tipl bych si, že to byla extrakce neplatný hlavičky z CSV (a tam byl nějakej takovejhle podivnej znak)

**Comment by odinuv** [comment]
jo, udela to CSV, ktery neni v utf-8, staci si pred to dat iconv, udelam z toho user error

**Comment by odinuv** [comment]
fixed in  f4962ae

**Comment by yustme** [comment]
Objevilo se to znova `CRITICAL: RuntimeException:Failed to create manifest: Malformed UTF-8 characters, possibly incorrectly encoded`. -> https://keboola.slack.com/archives/C09U3R1J4/p1559638894001000

Myslím, že by to měla být user exception, aby to tomu člověku řeklo, co s tím má udělat... "kámo měl by si tam prásknout iconv procesor a pak to bude v cajku"

**Comment by ondrejhlavacek** [comment]
@yustme V čem byl problém? V hlavičce?

**Comment by yustme** [comment]
@ondrejhlavacek popravdě jsem do toho víc nezabrušoval během zkoumání :confused: Viděl jsem chybu u procesoru a pak issue, který tomu odpovídalo. Mám se to pokusit nějaký rozkrejt?

**Comment by ondrejhlavacek** [comment]
stačí se asi mrknout do historie verzí konfigurace, jestli něco změnili?

**Comment by yustme** [comment]
Tak jsem tam mrknul. Žádná změna se v KBC neděla. Chyba u extractoru se ukázala 4.6:
![Snímek z 2019-06-14 09-55-38](https://user-images.githubusercontent.com/5272798/59493171-e891a180-8e8a-11e9-9599-59fb2335bb13.png)
Ale poslední změna byla 2 měsíce dozadu:
![Snímek z 2019-06-14 09-55-54](https://user-images.githubusercontent.com/5272798/59493207-f1827300-8e8a-11e9-8e21-9142b80eadea.png)

Nicméně změna, která opravila to rozbití je přidání decompress procesoru:
![Snímek z 2019-06-14 09-59-43](https://user-images.githubusercontent.com/5272798/59493472-2abae300-8e8b-11e9-8fd7-fe744d770d65.png)

Takže to nesjpíš na S3 začali zaboloval do zipu a to se projevilo jako "Malformed UTF-8". Možná by to spíš mělo říct, že to není textový soubor, ale zip ?

**Comment by pivnicek** [comment]
zase dneska 5x https://keboola.slack.com/archives/C09U3R1J4/p1560935455008100

**Comment by odinuv** [comment]
got a replicable config?

**Comment by odinuv** [comment]
> Takže to nesjpíš na S3 začali zaboloval do zipu a to se projevilo jako "Malformed UTF-8". Možná by to spíš mělo říct, že to není textový soubor, ale zip ?

to nebude tak snadny, protoze pokud je tam vicebajtovy kodovani (tj utf), tak je to binarni soubor, to, ze ti projde s tim pracovat jako s textem je sice fajn, ale nic to nezarucuje

**Comment by pivnicek** [comment]
> got a replicable config?

Unfortunately I don't have a ZD ticket for it yet.

**Comment by yustme** [comment]
@odinuv no a co zkontrolovat koncovku souboru?

**Comment by odinuv** [comment]
ta muze byt jakakoliv bohuzel
